apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount.rabbitmq }}
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
      - name: rabbitmq
        image: {{ .Values.image.rabbitmq }}
        ports:
        - containerPort: {{ .Values.service.rabbitmq.port }}
        - containerPort: 15672
        env:
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: ecommerce-secrets
              key: RABBITMQ_DEFAULT_USER
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: ecommerce-secrets
              key: RABBITMQ_DEFAULT_PASS
