apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - protocol: TCP
    port: {{ .Values.service.frontendPort }}
  selector:
    app: frontend