apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.service.mongo.port }}
  selector:
    app: mongo
  clusterIP: None  # Headless service for StatefulSet
